<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Auth\auth.json" />
    <None Remove="Images\dodo.png" />
    <None Remove="Tables\CreateCategory.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Auth\Auth.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="GitHub.Copilot.SDK" Version="0.3.0" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Nerdbank.MessagePack" Version="1.2.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\dodo.png" />
  </ItemGroup>

</Project>
